services:
  - type: web
    name: backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8888
      # URLs
      - key: API_URL
        value: https://ej-be.onrender.com/api
      - key: CLIENT_URL_V1
        value: https://ej-fe.onrender.com
      - key: MOBILE_URL_V1
        value: http://localhost:8686
      # Database
      - key: DATABASE_URL
        sync: false
      # JWT Secrets
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      # Mailjet Email
      - key: MJ_APIKEY_PUBLIC
        sync: false
      - key: MJ_APIKEY_PRIVATE
        sync: false
      - key: MJ_SENDER
        sync: false
